# Generated by Django 6.0.6 on 2026-09-01 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0002_fee_payment_fee_transport_f_student_36a6db_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fee',
            name='term',
            field=models.CharField(choices=[('January', 'January Term'), ('May', 'May Term'), ('September', 'September Term')], max_length=20),
        ),
    ]
